/*
 * Ambulance Equipment Api
 *
 * Ambulance Equipment management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: <your_email>
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package equipment

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

type EquipmentListAPI interface {

	// internal registration of api routes
	addRoutes(routerGroup *gin.RouterGroup)

	// GetEquipmentList - Provides the equipment list for a specific ambulance
	GetEquipmentList(ctx *gin.Context)

}

// partial implementation of EquipmentListAPI - all functions must be implemented in add on files
type implEquipmentListAPI struct {

}

func newEquipmentListAPI() EquipmentListAPI {
  return &implEquipmentListAPI{}
}

func (this *implEquipmentListAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodGet, "/ambulances/:ambulanceId/equipment", this.GetEquipmentList)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // GetEquipmentList - Provides the equipment list for a specific ambulance
// func (this *implEquipmentListAPI) GetEquipmentList(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//


