/*
 * Ambulance Equipment Api
 *
 * Ambulance Equipment management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: <your_email>
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package equipment

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

type AmbulanceListAPI interface {

	// internal registration of api routes
	addRoutes(routerGroup *gin.RouterGroup)

	// GetAmbulanceList - Provides the list of ambulances
	GetAmbulanceList(ctx *gin.Context)

}

// partial implementation of AmbulanceListAPI - all functions must be implemented in add on files
type implAmbulanceListAPI struct {

}

func newAmbulanceListAPI() AmbulanceListAPI {
  return &implAmbulanceListAPI{}
}

func (this *implAmbulanceListAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodGet, "/ambulances", this.GetAmbulanceList)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // GetAmbulanceList - Provides the list of ambulances
// func (this *implAmbulanceListAPI) GetAmbulanceList(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//


