/*
 * Ambulance Equipment Api
 *
 * Ambulance Equipment management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: <your_email>
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package equipment

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

type EquipmentAPI interface {

	// internal registration of api routes
	addRoutes(routerGroup *gin.RouterGroup)

	// CreateEquipment - Create new equipment to an ambulance
	CreateEquipment(ctx *gin.Context)

	// DeleteEquipmentById - Delete specific equipment
	DeleteEquipmentById(ctx *gin.Context)

	// GetEquipmentById - Get specific equipment details
	GetEquipmentById(ctx *gin.Context)

	// UpdateEquipmentById - Update specific equipment details
	UpdateEquipmentById(ctx *gin.Context)

}

// partial implementation of EquipmentAPI - all functions must be implemented in add on files
type implEquipmentAPI struct {

}

func newEquipmentAPI() EquipmentAPI {
  return &implEquipmentAPI{}
}

func (this *implEquipmentAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodPost, "/ambulances/:ambulanceId/equipment", this.CreateEquipment)
  routerGroup.Handle( http.MethodDelete, "/ambulances/:ambulanceId/equipment/:equipmentId", this.DeleteEquipmentById)
  routerGroup.Handle( http.MethodGet, "/ambulances/:ambulanceId/equipment/:equipmentId", this.GetEquipmentById)
  routerGroup.Handle( http.MethodPut, "/ambulances/:ambulanceId/equipment/:equipmentId", this.UpdateEquipmentById)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // CreateEquipment - Create new equipment to an ambulance
// func (this *implEquipmentAPI) CreateEquipment(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

// // DeleteEquipmentById - Delete specific equipment
// func (this *implEquipmentAPI) DeleteEquipmentById(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

// // GetEquipmentById - Get specific equipment details
// func (this *implEquipmentAPI) GetEquipmentById(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

// // UpdateEquipmentById - Update specific equipment details
// func (this *implEquipmentAPI) UpdateEquipmentById(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//


