/*
 * Ambulance Equipment Api
 *
 * Ambulance Equipment management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: <your_email>
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package equipment

import (
	"time"
)

type Equipment struct {

	// Unique identifier for the equipment
	Id string `json:"id"`

	// Name of the equipment
	Name string `json:"name"`

	// Availability status of the equipment
	Availability string `json:"availability"`

	// Date of the last inspection
	LastInspectionDate time.Time `json:"lastInspectionDate"`

	// Technical condition rating of the equipment
	TechnicalCondition int32 `json:"technicalCondition"`

	// Inspection interval in months
	InspectionInterval int32 `json:"inspectionInterval"`
}
