/*
 * Ambulance Equipment Api
 *
 * Ambulance Equipment management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: <your_email>
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package equipment

type Ambulance struct {

	// Unique identifier for the ambulance
	Id string `json:"id"`

	// Name of the ambulance
	Name string `json:"name"`

	Equipment []Equipment `json:"equipment,omitempty"`
}
